### ISSUE TITLE
Fix list index out of rang error

### ISSUE THREAD

**Issue by rjsears** [rjsears/chia_plot_manager#42]
drive_manager.py throws indexerror when no drives are available to look at. Need to do an exception

```
root@chianas03:~/plot_manager# ./drive_manager.py 
send_new_plot_notification() Started
update_receive_plot() Started
Total Serverwide Plots: 0
Traceback (most recent call last):
  File "./drive_manager.py", line 747, in <module>
    main()
  File "./drive_manager.py", line 740, in main
    update_receive_plot()
  File "./drive_manager.py", line 500, in update_receive_plot
    if current_plotting_drive == get_plot_drive_to_use():
  File "./drive_manager.py", line 391, in get_plot_drive_to_use
    return (natsorted(available_drives)[0][0])
IndexError: list index out of range
```

**Comment by rjsears** [comment]
Fixed in v0.8
